tags = [
    'MARTE_NODE_IVO3.DataCollection.Channel_182',  # 'top_04'
    'MARTE_NODE_IVO3.DataCollection.Channel_181',  # 'top_05'
    'MARTE_NODE_IVO3.DataCollection.Channel_184',  # 'top_06'
    'MARTE_NODE_IVO3.DataCollection.Channel_179',  # 'top_07'
    'MARTE_NODE_IVO3.DataCollection.Channel_178',  # 'top_08'
    'MARTE_NODE_IVO3.DataCollection.Channel_185',  # 'top_09'
    'MARTE_NODE_IVO3.DataCollection.Channel_183',  # 'top_10'
    'MARTE_NODE_IVO3.DataCollection.Channel_180',  # 'top_11'
    'MARTE_NODE_IVO3.DataCollection.Channel_004',  # 'top_12'
    'MARTE_NODE_IVO3.DataCollection.Channel_005',  # 'top_13'
    'MARTE_NODE_IVO3.DataCollection.Channel_003',  # 'top_14'
    'MARTE_NODE_IVO3.DataCollection.Channel_007',  # 'top_15'
    'MARTE_NODE_IVO3.DataCollection.Channel_000',  # 'top_16'
    'MARTE_NODE_IVO3.DataCollection.Channel_001',  # 'top_17'
    'MARTE_NODE_IVO3.DataCollection.Channel_002',  # 'top_18'
    'MARTE_NODE_IVO3.DataCollection.Channel_006',  # 'top_19'

    'MARTE_NODE_IVO3.DataCollection.Channel_190',  # 'out_04'
    'MARTE_NODE_IVO3.DataCollection.Channel_189',  # 'out_05'
    'MARTE_NODE_IVO3.DataCollection.Channel_192',  # 'out_06'
    'MARTE_NODE_IVO3.DataCollection.Channel_187',  # 'out_07'
    'MARTE_NODE_IVO3.DataCollection.Channel_186',  # 'out_08'
    'MARTE_NODE_IVO3.DataCollection.Channel_193',  # 'out_09'
    'MARTE_NODE_IVO3.DataCollection.Channel_191',  # 'out_10'
    'MARTE_NODE_IVO3.DataCollection.Channel_188',  # 'out_11'
    'MARTE_NODE_IVO3.DataCollection.Channel_012',  # 'out_12'
    'MARTE_NODE_IVO3.DataCollection.Channel_013',  # 'out_13'
    'MARTE_NODE_IVO3.DataCollection.Channel_011',  # 'out_14'
    'MARTE_NODE_IVO3.DataCollection.Channel_015',  # 'out_15'
    'MARTE_NODE_IVO3.DataCollection.Channel_008',  # 'out_16'
    'MARTE_NODE_IVO3.DataCollection.Channel_009',  # 'out_17'
    'MARTE_NODE_IVO3.DataCollection.Channel_010',  # 'out_18'
    'MARTE_NODE_IVO3.DataCollection.Channel_014',  # 'out_19'
]

